/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMonitoringRouteImport } from './routes/app.monitoring'
import { Route as AppMaintenanceRouteImport } from './routes/app.maintenance'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppLinesRouteImport } from './routes/app.lines'
import { Route as AppDevicesRouteImport } from './routes/app.devices'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppControlRouteImport } from './routes/app.control'
import { Route as AppArchitectureRouteImport } from './routes/app.architecture'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppLinesRoute = AppLinesRouteImport.update({
  id: '/lines',
  path: '/lines',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppControlRoute = AppControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AppRoute,
} as any)
const AppArchitectureRoute = AppArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/app/ai': typeof AppAiRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/control': typeof AppControlRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/lines': typeof AppLinesRoute
  '/app/logs': typeof AppLogsRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/app/ai': typeof AppAiRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/control': typeof AppControlRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/lines': typeof AppLinesRoute
  '/app/logs': typeof AppLogsRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/app/ai': typeof AppAiRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/control': typeof AppControlRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/lines': typeof AppLinesRoute
  '/app/logs': typeof AppLogsRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/api/ai-chat'
    | '/app/ai'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/architecture'
    | '/app/control'
    | '/app/dashboard'
    | '/app/devices'
    | '/app/lines'
    | '/app/logs'
    | '/app/maintenance'
    | '/app/monitoring'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/users'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/ai-chat'
    | '/app/ai'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/architecture'
    | '/app/control'
    | '/app/dashboard'
    | '/app/devices'
    | '/app/lines'
    | '/app/logs'
    | '/app/maintenance'
    | '/app/monitoring'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/users'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/api/ai-chat'
    | '/app/ai'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/architecture'
    | '/app/control'
    | '/app/dashboard'
    | '/app/devices'
    | '/app/lines'
    | '/app/logs'
    | '/app/maintenance'
    | '/app/monitoring'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/users'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring': {
      id: '/app/monitoring'
      path: '/monitoring'
      fullPath: '/app/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/maintenance': {
      id: '/app/maintenance'
      path: '/maintenance'
      fullPath: '/app/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lines': {
      id: '/app/lines'
      path: '/lines'
      fullPath: '/app/lines'
      preLoaderRoute: typeof AppLinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devices': {
      id: '/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/control': {
      id: '/app/control'
      path: '/control'
      fullPath: '/app/control'
      preLoaderRoute: typeof AppControlRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/architecture': {
      id: '/app/architecture'
      path: '/architecture'
      fullPath: '/app/architecture'
      preLoaderRoute: typeof AppArchitectureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppArchitectureRoute: typeof AppArchitectureRoute
  AppControlRoute: typeof AppControlRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppLinesRoute: typeof AppLinesRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppArchitectureRoute: AppArchitectureRoute,
  AppControlRoute: AppControlRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppLinesRoute: AppLinesRoute,
  AppLogsRoute: AppLogsRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAiChatRoute: ApiAiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
